name: "Get & cache dependencies"
description: "Get and cache dependencies for faster builds"
inputs:
  caching:
    description: "Whether to cache dependencies or not."
    required: false
    default: "true"
outputs:
  used-cache:
    description: "Whether the cache was used"
    value: ${{ steps.installation.outputs.cache }}
runs:
  using: composite
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: installation
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      shell: bash
      run: |
        npm ci
        echo "cache='${{inputs.caching}}'" >> $GITHUB_OUTPUT
